# Generated by Django 5.2.4 on 2025-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
    ]
