# Generated by Django 5.2.4 on 2025-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
