# Generated by Django 5.2.4 on 2025-09-30 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('api_type', models.CharField(choices=[('rss', 'RSS'), ('rest', 'REST'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=50)),
                ('endpoint', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fetch_interval_seconds', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=400)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.feedsource')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['published_at'], name='feeds_feedi_publish_649096_idx'), models.Index(fields=['is_active'], name='feeds_feedi_is_acti_6464dd_idx'), models.Index(fields=['content_hash'], name='feeds_feedi_content_a063e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external')],
            },
        ),
    ]
