# Generated by Django 5.2.4 on 2025-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='feedsource',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
